const fs = require('fs');
const path = require('path');

const USERNAME = 'ErBharatMalhotra';
const TOKEN = process.env.GITHUB_TOKEN;
const PROFILE_DIR = path.join(__dirname, '../../profile');

// ─────────────────────────────────────────────
// GraphQL Query
// ─────────────────────────────────────────────
const QUERY = `
query($username: String!) {
  user(login: $username) {
    name
    login
    avatarUrl
    repositories(ownerAffiliations: OWNER) {
      totalCount
      nodes {
        name
        description
        stargazerCount
        forkCount
        primaryLanguage { name color }
        isPrivate
      }
    }
    contributionsCollection {
      contributionCalendar {
        totalContributions
        weeks {
          contributionDays {
            contributionCount
            date
          }
        }
      }
    }
    pullRequests { totalCount }
    issues { totalCount }
    followers { totalCount }
    following { totalCount }
    pinnedItems(first: 6, types: REPOSITORY) {
      nodes {
        ... on Repository {
          name
          description
          stargazerCount
          url
        }
      }
    }
  }
  rateLimit {
    remaining
  }
}
`;

// ─────────────────────────────────────────────
// GitHub API Call
// ─────────────────────────────────────────────
async function fetchGitHubData() {
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${TOKEN}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query: QUERY, variables: { username: USERNAME } }),
  });

  const json = await res.json();
  if (json.errors) {
    console.error('GraphQL errors:', json.errors);
    throw new Error('Failed to fetch GitHub data');
  }
  return json.data;
}

// ─────────────────────────────────────────────
// SVG Helpers
// ─────────────────────────────────────────────
function escapeXml(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const COLORS = {
  bg: '#0d1117',
  cardBg: '#161b22',
  border: '#30363d',
  text: '#e6edf3',
  textSecondary: '#8b949e',
  green: '#39d353',
  purple: '#a855f7',
  blue: '#58a6ff',
};

// ─────────────────────────────────────────────
// Generate stats.svg
// ─────────────────────────────────────────────
function generateStatsSvg(data) {
  const user = data.user;
  const cal = user.contributionsCollection.contributionCalendar;
  const repos = user.repositories;
  const totalStars = repos.nodes.reduce((sum, r) => sum + r.stargazerCount, 0);

  const stats = [
    { label: 'Total Stars', value: totalStars, color: COLORS.purple },
    { label: 'Total PRs', value: user.pullRequests.totalCount, color: COLORS.green },
    { label: 'Total Issues', value: user.issues.totalCount, color: COLORS.blue },
    { label: 'Contributions', value: cal.totalContributions, color: COLORS.green },
  ];

  const statRows = stats.map((s, i) => {
    const y = 120 + i * 55;
    return `
    <text x="40" y="${y}" fill="${COLORS.textSecondary}" font-family="Segoe UI, Arial, sans-serif" font-size="14">${s.label}</text>
    <text x="290" y="${y}" fill="${s.color}" font-family="Segoe UI, Arial, sans-serif" font-size="20" font-weight="bold" text-anchor="end">${s.value.toLocaleString()}</text>`;
  }).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="350" height="370" viewBox="0 0 350 370">
  <defs>
    <style>
      text { font-family: "Segoe UI", Arial, sans-serif; }
    </style>
  </defs>

  <!-- Background -->
  <rect width="350" height="370" rx="10" fill="${COLORS.bg}" stroke="${COLORS.border}" stroke-width="1"/>

  <!-- Avatar -->
  <clipPath id="avatarClip"><circle cx="45" cy="45" r="20"/></clipPath>
  <image href="${user.avatarUrl}" x="25" y="25" width="40" height="40" clip-path="url(#avatarClip)"/>

  <!-- Name -->
  <text x="75" y="42" fill="${COLORS.text}" font-size="16" font-weight="bold">${escapeXml(user.name || user.login)}</text>
  <text x="75" y="58" fill="${COLORS.textSecondary}" font-size="12">@${escapeXml(user.login)}</text>

  <!-- Stats -->
  <line x1="30" y1="85" x2="320" y2="85" stroke="${COLORS.border}" stroke-width="1"/>
  <text x="30" y="105" fill="${COLORS.textSecondary}" font-size="12">GitHub Stats</text>
  ${statRows}

  <!-- Footer -->
  <text x="175" y="355" fill="${COLORS.textSecondary}" font-size="10" text-anchor="middle">Generated by GitHub Actions • ${new Date().toISOString().split('T')[0]}</text>
</svg>`;
}

// ─────────────────────────────────────────────
// Generate top-langs.svg
// ─────────────────────────────────────────────
function generateTopLangsSvg(data) {
  const repos = data.user.repositories.nodes.filter(r => !r.isPrivate);
  const langMap = {};

  repos.forEach(r => {
    if (r.primaryLanguage) {
      const lang = r.primaryLanguage.name;
      if (!langMap[lang]) langMap[lang] = { color: r.primaryLanguage.color || '#8b949e', count: 0 };
      langMap[lang].count++;
    }
  });

  const sorted = Object.entries(langMap)
    .sort((a, b) => b[1].count - a[1].count)
    .slice(0, 8);

  const total = sorted.reduce((sum, [, v]) => sum + v.count, 0);

  const barWidth = 260;
  const barHeight = 14;
  const barX = 40;
  const barStartY = 130;

  const langRows = sorted.map(([name, info], i) => {
    const y = barStartY + i * 30;
    const pct = (info.count / total) * 100;
    const w = (pct / 100) * barWidth;

    return `
    <text x="40" y="${y - 5}" fill="${COLORS.textSecondary}" font-size="12">${escapeXml(name)}</text>
    <rect x="${barX}" y="${y}" width="${barWidth}" height="${barHeight}" rx="7" fill="${COLORS.border}"/>
    <rect x="${barX}" y="${y}" width="${w}" height="${barHeight}" rx="7" fill="${info.color}"/>
    <text x="${barX + w + 8}" y="${y + 11}" fill="${COLORS.textSecondary}" font-size="11">${pct.toFixed(1)}%</text>`;
  }).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="350" height="${barStartY + sorted.length * 30 + 50}" viewBox="0 0 350 ${barStartY + sorted.length * 30 + 50}">
  <defs>
    <style>text { font-family: "Segoe UI", Arial, sans-serif; }</style>
  </defs>

  <rect width="350" height="${barStartY + sorted.length * 30 + 50}" rx="10" fill="${COLORS.bg}" stroke="${COLORS.border}" stroke-width="1"/>

  <text x="40" y="40" fill="${COLORS.text}" font-size="16" font-weight="bold">Most Used Languages</text>
  <text x="40" y="60" fill="${COLORS.textSecondary}" font-size="12">Based on public repositories</text>

  <line x1="30" y1="80" x2="320" y2="80" stroke="${COLORS.border}" stroke-width="1"/>
  <text x="40" y="105" fill="${COLORS.textSecondary}" font-size="12">Languages (${sorted.length})</text>
  <text x="290" y="105" fill="${COLORS.textSecondary}" font-size="12" text-anchor="end">${repos.length} repos</text>

  ${langRows}
</svg>`;
}

// ─────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────
async function main() {
  console.log('📊 Fetching GitHub data for', USERNAME, '...');
  const data = await fetchGitHubData();
  console.log('✅ Data fetched!');

  fs.mkdirSync(PROFILE_DIR, { recursive: true });

  const statsSvg = generateStatsSvg(data);
  fs.writeFileSync(path.join(PROFILE_DIR, 'stats.svg'), statsSvg);
  console.log('✅ stats.svg generated');

  const langsSvg = generateTopLangsSvg(data);
  fs.writeFileSync(path.join(PROFILE_DIR, 'top-langs.svg'), langsSvg);
  console.log('✅ top-langs.svg generated');

  console.log('🎉 All SVGs generated successfully!');
}

main().catch(err => {
  console.error('❌ Error:', err.message);
  process.exit(1);
});
